[package]
name = "jeff-discord"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
chrono = "0.4"
colorsys = "=0.6.4"
regex = "1"
tokio = { version = "1", features = ["full"]  }
serenity = "0.10"
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "postgres"] }

