services:
    app:
        image: ghcr.io/e8035669/jeff-discord:main
        build: .
        volumes:
            - ./dbdata:/dbdata
        working_dir: /dbdata
        env_file:
            - .env

