[project]
name = "llm_python_client"
version = "0.1.0"
description = "Add a short description here"
authors = ["Yu-Ren Zhang <e8035669@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.11.*"
openai = ">=1.41.1,<2"
