services:
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_DEBUG=1
    volumes:
      - ./ollama:/root/.ollama

  web:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3000:8080
    environment:
      - WEBUI_AUTH=false
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./open-webui:/app/backend/data

